### ISSUE TITLE
TAB Parser behaviour for blank entries in a column

### ISSUE THREAD

**Issue by KeywanHP** [Rothamsted/knetbuilder#31]
The below TAB parser snippet currently creates an "empty" concept even for blank entries in a given column. The desired behaviour would be to ignore blank entries.

```xml
	<concept id = "gene">
		<class>Gene</class>
		<data-source>ARAGWAS</data-source>
		<accession data-source="TAIR">
			<column index='1'/>
		</accession>
	</concept>
```

**Comment by marco-brandizi** [comment]
@KeywanHP, @jparsons2222, please someone test it with real data and close this if it works.

**Comment by KeywanHP** [comment]
This issue still exists. It is not related to a specific dataset but is a generic TAB parser enhancement request. For blank cells, the current logic seems to be to create a concept without any properties (ghost concept). The better logic would be to create concepts only for non-empty cells. 

Do you agree @marco-brandizi @jparsons2222 ?

**Comment by marco-brandizi** [comment]
@KeywanHP, It should work as per the unit tests about it:

[Sample file](https://github.com/Rothamsted/knetbuilder/blob/master/ondex-knet-builder/modules/tab-parser-2/src/test/resources/ondex_tutorial_2016/gene_example_holes.tsv)
[Config file](https://github.com/Rothamsted/knetbuilder/blob/master/ondex-knet-builder/modules/tab-parser-2/src/test/resources/ondex_tutorial_2016/gene_example_parser_cfg.xml)
[test about missing values](https://github.com/Rothamsted/knetbuilder/blob/3e4ce8e2a83ca2e487a36d89a044df9c8b354972/ondex-knet-builder/modules/tab-parser-2/src/test/java/net/sourceforge/ondex/plugins/tab_parser_2/ParserTest.java#L180)

As you can see,
* O43426 is created as a concept node, but not linked to anything, cause its row hasn't any other element
* Same for ENSG00000185345, since no protein accession is reported in the corresponding row
* ENSG00000184381 is created without any attribute (having the corresponding cells empty)

Shouldn't it behave this way? Do you have an example + how you expect it to be parsed?
Are you using the [latest version](https://github.com/Rothamsted/knetbuilder/wiki/Downloads)?

**Comment by KeywanHP** [comment]
This is great. Exactly the behaviour that I would be expecting. We have been using knetbuilder 3.0. Should switch to the latest version now! @jparsons2222

**Comment by marco-brandizi** [comment]
Closing as fixed.
