### ISSUE TITLE
Use of semanticmotifs?

### ISSUE THREAD

**Issue by man4ish** [Rothamsted/knetbuilder#36]
How do you define semanticmotifs.txt for a new species? Where is it used? Is it important for building network or important for mining network or both?

**Comment by marco-brandizi** [comment]
See this [documentation page](https://github.com/Rothamsted/knetminer/wiki/Semantic-Motif-Searching-in-Knetminer). When you build a new network, it might be the case that the kind of queries you want to use to associate genes to relevant other entities are the same as the ones used in some other [pre-configured dataset](github.com/Rothamsted/knetminer/blob/master/datasets), for instance, because your new data set is about a species that is similar to one we already support.

In that case, reusing the same queries should work fine. Else, existing queries are usually where we start from anyway.

Also notes that for each of the pre-defined datasets, we have graphical representations of the relations the queries explore. Such representations are at `datasets/xxxx/ws/neo4j/state-machine-queries/state-machine.svg`, as in [this example](https://github.com/Rothamsted/knetminer/blob/master/datasets/arabidopsis/ws/neo4j/state-machine-queries/state-machine.svg). The graphs are made from semanticmotifs.txt using [this tool](https://github.com/Rothamsted/knetminer/wiki/Semantic-Motif-Searching-in-Knetminer#the-state-machine-converter-and-visual-renderer) (unfortunately, its documentation is still to be improved, if you need I can work on it next week).
