### ISSUE TITLE
Extend tmbased plugin with words to exclude from search

### ISSUE THREAD

**Issue by KeywanHP** [Rothamsted/knetbuilder#65]
The tmbased mapping plugin can be extended with a new file parameter which contains words that should be excluded from the text mining search. For example, the file could contain a list of bad gene names such as ACT, INC, SUB, MAX etc (one name per line). 

The code is here: https://github.com/Rothamsted/knetbuilder/blob/master/ondex-knet-builder/modules/textmining/src/main/java/net/sourceforge/ondex/mapping/tmbased/Mapping.java

Can be implemented as simple `if(conceptName==STOPWORD) continue;` or we can look into Lucene StopFilter https://lucene.apache.org/core/8_0_0/analyzers-common/org/apache/lucene/analysis/core/StopFilter.html. @marco-brandizi  please advice before we start implementing.

```xml
        <Mapping name="tmbased">
            <Arg name="OnlyPreferredNames">true</Arg>   
            <Arg name="UseFullText">false</Arg>
            <Arg name="Search">exact</Arg>
            <Arg name="graphId">default</Arg>
            **<Arg name="geneNameStopWords">/path/to/file.txt</Arg>** <!-- eg List of gene names to exclude -->
            <Arg name="ConceptClass">Gene</Arg>
            <Arg name="ConceptClass">Trait</Arg>
        </Mapping>
```

**Comment by marco-brandizi** [comment]
@jojicunnunni I've given a look to this, and using Lucene stop-words doesn't seem worthwhile for such a simple filtering. It's simpler to add something like `bool isGeneNameStopWord( String name, Set<String> stopWords )` and use it [here](https://github.com/Rothamsted/knetbuilder/blob/a7c0fa82afb1e19840d9c8723a7ffde0b8356e54/ondex-knet-builder/modules/textmining/src/main/java/net/sourceforge/ondex/mapping/tmbased/Mapping.java#L157), before `if (!validName(...))`, essentially the same way.

As for the implementation of this new method, `Mapping.start()` should create a `Set<String>` by reading from the file given with the `geneNameFilters` file (assuming it has one word per line) and then pass this to the method above).  

I'm proposing this different argument name, should be more meaningful.

**Comment by marco-brandizi** [comment]
I've merged this on master. @KeywanHP, @jparsons2222, please confirm it works and possibly close this ticket. The binaries are deployed at the usual place, the parameter to be used in the XML is `GeneNameStopWords`.  

@jojicunnunni have a look at the last version of the test class (on master), cause it has useful examples of various ways to query and manipulate ONDEX graph entities, and likely, you'll find them useful in future.

**Comment by marco-brandizi** [comment]
@jojicunnunni sorry to bother with this again, there is no test about the stop word feature:
`testStopWords()` runs with a stop word file, but then it only checks that two selected Publication concepts have been linked to gene concepts.  This is a good test for the regular operation, and it would be worth renaming it (eg, `testCreatedLinks()`) and invoke the plugin without the stop word option.

However, **the real `testStopWords()`** should first call the plugin **without**  the stop word option and verify that at least one link between a Gene and a Publication both mentioning a word like 'MAX' (ie, one of them in the `stop-words.txt` file) is indeed created. Then, it should repeat everything **with** the stop-words option and verify that the same link about 'MAX' *is not* created. The point of this is the stop words are actually ignored, and the first part is to ensure that the test doesn't succeed because the linking never happens. Probably, the best way to write this test is to initially create two concepts with suitable attributes  (ie, containing 'MAX') programmatically. Alternatively, it's possible to inspect the already used OXL file and find a relevant concept pair, but maybe it isn't as well practical.

**Comment by Arnedeklerk** [comment]
@marco-brandizi Please review Joji's changes when you get the time :)

**Comment by KeywanHP** [comment]
Suggest to change GeneNameStopWords to StopWords. @jojicunnunni

**Comment by marco-brandizi** [comment]
@KeywanHP, param changed into `ConceptNameStopWords`.

@jojicunnunni I think it's good enough now, thanks. I've just done a few [final refinements](#5964e0a). I'm closing this.
